resource_group_name           = "rg-dev"
location                      = "eastus"
security_group_name           = "nsg-dev"
virtual_network_name          = "vnet-dev"
virtual_network_address_space = ["10.0.0.0/16"]
dns_servers                   = ["8.8.8.8", "4.4.4.4"]
subnet1_name                  = "snet-dev1"
subnet2_name                  = "snet-dev2"
subnet1_address_prefix        = "10.0.1.0/24"
subnet2_address_prefix        = "10.0.2.0/24"